# Format: FROM=TO
# This configuration file is used no matching application/window config is found

# Normal mappings
BTN_SIDE=COPY_MACRO
BTN_EXTRA=PASTE_MACRO

# layershift button (should really only use one)
#LAYER_SHIFT_TOGGLE=KEY_F24
LAYER_SHIFT_HOLD=KEY_F24 # I program my 3rd mouse button to use this key

# Layer shift mappings
[layershift]
BTN_SIDE=KEY_LEFTSHIFT
BTN_EXTRA=KEY_LEFTMETA
